### ISSUE TITLE
Session issues

### ISSUE THREAD

**Issue by kachmul2004** [v1ctor/huawei-api-client#1]
Hi, I am new to Kotlin and wanted to try out this client. I have the python version and it works fine with a Huawei e5573 router. I was trying out your Sample code and it seems that it skips something when trying to use one of the API's (send SMSApi) for example. It always shows an error that **"No token you need to login again."**

**I also tried to make my own API to turn data on or off using the code below:**

`
package org.buldakov.huawei.modem.api

import org.buldakov.huawei.modem.client.ModemClient
import org.buldakov.huawei.modem.model.*

class DApi(private val modemClient: ModemClient) {

    fun sond(enable: Int): Boolean {
        val request = Enable(enable = enable)
        val response = modemClient.makePost("/api/dialup/mobile-dataswitch", request, OKResponse::class.java)
        return response?.value == "OK"
    }
}
`

**Then to try and turn of data , I run this code in main:**

`val password = "admin"
    val username = "admin"
    val ip = "https://youtube.com"

    val modemClient = ModemClient("http://192.168.8.1")
    modemClient.login(username, password)
    var dApi = DApi(modemClient)
    dApi.sond(0)
`
**in model, i have:**

`package org.buldakov.huawei.modem.model

import com.fasterxml.jackson.annotation.JsonRootName
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty

@JsonRootName("request")
class Enable(
    @JacksonXmlProperty(localName = "dataswitch") val enable: Int,
)
`

**When I run main, i get :**
`2021-08-19 11:10:52.175 [main] WARN  o.b.huawei.modem.client.ModemClient.token(49) - No token you need to login again.
Exception in thread "main" java.lang.NullPointerException
	at org.buldakov.huawei.modem.client.ModemClient.addVerificationToken(ModemClient.kt:150)
	at org.buldakov.huawei.modem.client.ModemClient.makePost(ModemClient.kt:135)
	at org.buldakov.huawei.modem.client.ModemClient.makePost(ModemClient.kt:105)
	at org.buldakov.huawei.modem.api.DApi.sond(DApi.kt:10)
	at org.buldakov.huawei.modem.SampleKt.main(Sample.kt:23)
	at org.buldakov.huawei.modem.SampleKt.main(Sample.kt)
`

**Comment by v1ctor** [comment]
Hi @kachmul2004 , I really unsure how huawei E8372 is different from e5573. When I used python client I had problems to make it work with my modem, I realised that the API is different between different versions of the modem software. 
So I had to reverse engineer it and write my own client. 

You can try to use WireShark and try to do some action in the modem web ui to see what is happening, it will help you to understand where do we miss the token.

**Comment by kachmul2004** [comment]
hi @v1ctor I found the problem here

`val request = Request.Builder().url("$baseUrl/api/user/login").post(body)
            .header("__RequestVerificationToken", loginToken!!)
            **.header("Cookie", sessionId!!)**
            .header("X-Requested-With", "XMLHttpRequest")
            .build()`

In your code it was **.header("Cookie", "SessionId=$sessionId!!)"**, but the **_private var sessionid_** string was already in the format **_"Sessionid=xxxxxxxxxxxxxx"_**.  So the end result was **_SessionId=Sessionid=xxxxxxxxxxxxxx_**

**Comment by v1ctor** [comment]
Hi @kachmul2004, thank you so much for finding the issue! 

However how I mentioned before it looks like a problem with Huawei e5573 software, on my huawei E8372 there is no such problem.

However I think that if you you remove "Sessionid=" prefix it will work in both cases.

So, please send me a pull requests and I will be happy to accept it! 

Thanks!

**Comment by kachmul2004** [comment]
@v1ctor Thanks. I made a lot of custom changes to make it work for the automation I needed, so I don't think it will be necessary to make a pull request

**Comment by v1ctor** [comment]
Cool! Feel free to contribute parts if you think that they will be valuable for others. I will close the issue.
