### ISSUE TITLE
API request to restart the modem

### ISSUE THREAD

**Issue by joaotinoco** [v1ctor/huawei-api-client#2]
Is it possible to send a command to the router so it restarts?

   After login: 
              val modemClient = ModemClient("http://192.168.8.1")
              modemClient.login("admin", password)
   
  It would be greate to do something like that (for example):
             modemClient.reset()

**Comment by kachmul2004** [comment]
@joaotinoco 
under "Remarks", you will see what value to put between `"<control><control>"`, and what it does.

Method: POST 
request:
Code:
```
<request> 
  <control></control> 
</request>
```

answer:
Code:
`<Response> OK </ response>`

Remarks:
Control: 
1 - restart of the device 
2 - reset the configuration (no information on how to enter a saved configuration file. You may use the file http://192.168.8.1/nvram.bak ) 
3 - backup configuration (configuration is available at http://192.168.8.1/nvram.bak . This is a base64-encoded) 
4 - shutdown

**Comment by joaotinoco** [comment]
That is awesome :D
Thanks for the clarification!!!

**Comment by v1ctor** [comment]
Awesome staff! Would you like to contribute this feature?
